name: 🚀 Deploy Web com Expo

on:
  push:
    branches:
      - main  # ou a branch que você usa para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v3

      - name: 🔧 Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Instalar dependências
        run: npm install

      - name: 🔐 Criar arquivo .env com Firebase Secrets
        run: |
          echo "EXPO_PUBLIC_APPKEY=${{ secrets.EXPO_PUBLIC_APPKEY }}" >> .env
          echo "EXPO_PUBLIC_AUTHDOMAIN=${{ secrets.EXPO_PUBLIC_AUTHDOMAIN }}" >> .env
          echo "EXPO_PUBLIC_PROJECTID=${{ secrets.EXPO_PUBLIC_PROJECTID }}" >> .env
          echo "EXPO_PUBLIC_STORAGEBUCKET=${{ secrets.EXPO_PUBLIC_STORAGEBUCKET }}" >> .env
          echo "EXPO_PUBLIC_MESSAGINGSENDERID=${{ secrets.EXPO_PUBLIC_MESSAGINGSENDERID }}" >> .env
          echo "EXPO_PUBLIC_APPID=${{ secrets.EXPO_PUBLIC_APPID }}" >> .env
          echo "EXPO_PUBLIC_WEBCLIENTID=${{ secrets.EXPO_PUBLIC_WEBCLIENTID }}" >> .env
          echo "EXPO_PUBLIC_ANDROIDCLIENT_ID=${{ secrets.EXPO_PUBLIC_ANDROIDCLIENT_ID }}" >> .env

      - name: 🌐 Build Expo Web
        run: npx expo export --platform web

      # Opcional: deploy automático para um serviço (Netlify, Vercel, Firebase Hosting, etc.)
      # Você pode adicionar aqui o comando de deploy, por exemplo para Firebase Hosting:
      # - name: 🚀 Deploy para Firebase Hosting
      #   run: npx firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
